# Generated by Django 5.2.11 on 2026-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerStatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date', models.DateField(verbose_name='수집 일자')),
                ('hour', models.IntegerField(verbose_name='수집 시간(시)')),
                ('busiid', models.CharField(max_length=50, verbose_name='사업자 ID')),
                ('stat_1_count', models.IntegerField(default=0, verbose_name='통신이상(1)')),
                ('stat_2_count', models.IntegerField(default=0, verbose_name='충전대기(2)')),
                ('stat_3_count', models.IntegerField(default=0, verbose_name='충전중(3)')),
                ('stat_4_count', models.IntegerField(default=0, verbose_name='운영중지(4)')),
                ('stat_5_count', models.IntegerField(default=0, verbose_name='점검중(5)')),
                ('stat_9_count', models.IntegerField(default=0, verbose_name='상태미확인(9)')),
            ],
            options={
                'verbose_name': '시간별 충전기 상태 요약',
                'verbose_name_plural': '시간별 충전기 상태 요약 목록',
                'unique_together': {('collected_date', 'hour', 'busiid')},
            },
        ),
    ]
