# Generated by Django 5.2.11 on 2026-02-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_chargerstatsummary_cpstatsum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpstatsum',
            old_name='busiid',
            new_name='businm',
        ),
        migrations.AlterUniqueTogether(
            name='cpstatsum',
            unique_together={('collected_date', 'hour', 'businm')},
        ),
    ]
