# Generated by Django 5.2.11 on 2026-02-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_busiid_cpstatsum_businm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpstatsum',
            old_name='businm',
            new_name='busiid',
        ),
        migrations.AlterUniqueTogether(
            name='cpstatsum',
            unique_together={('collected_date', 'hour', 'busiid')},
        ),
    ]
